[package]
name = "cancer"
version = "0.1.0"
edition = "2021"
authors = ["Weidaicheng <wdcdavyc@outlook.com>"]
description = "A Framework for CLI Apps in Rust"
repository = "https://github.com/Weidaicheng/cancer"

[workspace]
members = ["examples/*"]

[dependencies]
